# Change these first
owner: alfonso100 # Your GitHub organization or username, where this repository lives
repo: furry-octo-enigma # The name of this repository

sites:
  - name: WP-Rocket.me
    url: https://wp-rocket.me
  - name: WP-Rocket - License Validation
    url: https://wp-rocket.me/valid_key.php  
  - name: RocketCDN.com
    url: https://rocketcdn.me/
  - name: SaaS - Remove Unused CSS generation service (CPCSS)
    url: https://central-saas.wp-rocket.me/
  - name: SaaS - Critical Path CSS generation service (CPCSS)
    url: https://cpcss.wp-rocket.me/ui
  - name: Imagify.io
    url: https://imagify.io/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: alfonso100.github.io
  baseUrl: /furry-octo-enigma
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: WP Media - services stauts
  introTitle: "Welcome to **WP Media's Service status page**, powered entirely by GitHub."
  introMessage: This is a real time status page. If you face any issues please contact the support.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
